<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\Fonts\icon-radio\config.json" />
  </ItemGroup>


	<ItemGroup>
		<PackageReference Include="IVSoftware.Portable.Common" Version="1.0.0-beta" />
		<PackageReference Include="IVSoftware.Portable.WatchdogTimer" Version="*" />
		<PackageReference Include="IVSoftware.Portable.Disposable" Version="2.0.0" />
		<PackageReference Include="IVSoftware.Portable.SQLiteMarkdown" Version="1.0.2-rc" />
	</ItemGroup>


	<ItemGroup>
	  <ProjectReference Include="..\..\..\IVSoftware.GlyphProvider\IVSoftware.GlyphProvider.Portable\IVSoftware.GlyphProvider.Portable.csproj" />
	  <ProjectReference Include="..\IVSoftware.Portable.Collections\IVSoftware.Portable.Collections.csproj" />
	</ItemGroup>

</Project>
